app/backend/chrev/urls.py
from django.urls import path
from chrev import chrevViews
app_name='chrev'

urlpatterns = [





	
	
	#Apps

	path('post_details/',chrevViews.post_details,name="post-details"),

	path('email_compose/',chrevViews.email_compose,name="email-compose"),
	path('email_inbox/',chrevViews.email_inbox,name="email-inbox"),
	path('email_read/',chrevViews.email_read,name="email-read"),

	#Calender
	path('app_calender/',chrevViews.app_calender,name="app-calender"),
	#shop
	path('ecom_checkout/',chrevViews.ecom_checkout,name="ecom-checkout"),
	path('ecom_customers/',chrevViews.ecom_customers,name="ecom-customers"),
	path('ecom_invoice/',chrevViews.ecom_invoice,name="ecom-invoice"),
	path('ecom_product_detail/',chrevViews.ecom_product_detail,name="ecom-product-detail"),
	path('ecom_product_grid/',chrevViews.ecom_product_grid,name="ecom-product-grid"),
	path('ecom_product_list/',chrevViews.ecom_product_list,name="ecom-product-list"),
	path('ecom_product_order/',chrevViews.ecom_product_order,name="ecom-product-order"),
	
	#charts
	path('chart_chartist/',chrevViews.chart_chartist,name="chart-chartist"),
	path('chart_chartjs/',chrevViews.chart_chartjs,name="chart-chartjs"),
	path('chart_flot/',chrevViews.chart_flot,name="chart-flot"),
	path('chart_morris/',chrevViews.chart_morris,name="chart-morris"),
	path('chart_peity/',chrevViews.chart_peity,name="chart-peity"),
	path('chart_sparkline/',chrevViews.chart_sparkline,name="chart-sparkline"),

	#Components
	#---->Bootstrap
	path('ui_accordion/',chrevViews.ui_accordion,name="ui-accordion"),
	path('ui_alert/',chrevViews.ui_alert,name="ui-alert"),
	path('ui_badge/',chrevViews.ui_badge,name="ui-badge"),
	path('ui_button/',chrevViews.ui_button,name="ui-button"),
	path('ui_modal/',chrevViews.ui_modal,name="ui-modal"),
	path('ui_button_group/',chrevViews.ui_button_group,name="ui-button-group"),
	path('ui_list_group/',chrevViews.ui_list_group,name="ui-list-group"),
	path('ui_media_object/',chrevViews.ui_media_object,name="ui-media-object"),
	path('ui_card/',chrevViews.ui_card,name="ui-card"),
	path('ui_carousel/',chrevViews.ui_carousel,name="ui-carousel"),
	path('ui_dropdown/',chrevViews.ui_dropdown,name="ui-dropdown"),
	path('ui_popover/',chrevViews.ui_popover,name="ui-popover"),
	path('ui_progressbar/',chrevViews.ui_progressbar,name="ui-progressbar"),
	path('ui_tab/',chrevViews.ui_tab,name="ui-tab"),
	path('ui_typography/',chrevViews.ui_typography,name="ui-typography"),
	path('ui_pagination/',chrevViews.ui_pagination,name="ui-pagination"),
	path('ui_grid/',chrevViews.ui_grid,name="ui-grid"),

	#Components
	#---->Plugins
	path('uc_select2/',chrevViews.uc_select2,name="uc-select2"),
	path('uc_nestable/',chrevViews.uc_nestable,name="uc-nestable"),
	path('uc_noui_slider/',chrevViews.uc_noui_slider,name="uc-noui-slider"),
	path('uc_sweetalert/',chrevViews.uc_sweetalert,name="uc-sweetalert"),
	path('uc_toastr/',chrevViews.uc_toastr,name="uc-toastr"),
	path('map_jqvmap/',chrevViews.map_jqvmap,name="map-jqvmap"),
	path('uc_lightgallery/',chrevViews.uc_lightgallery,name="uc-lightgallery"),
	#Widget Basic
	path('widget_basic/',chrevViews.widget_basic,name="widget-basic"),
	#forms
	path('form_element/',chrevViews.form_element,name="form-element"),
	path('form_wizard/',chrevViews.form_wizard,name="form-wizard"),
	path('form_ckeditor/',chrevViews.form_ckeditor,name="form-ckeditor"),
	path('form_pickers/',chrevViews.form_pickers,name="form-pickers"),
	path('form_validation_jquery/',chrevViews.form_validation_jquery,name="form-validation-jquery"),

	#table
	path('table_bootstrap_basic/',chrevViews.table_bootstrap_basic,name="table-bootstrap-basic"),
	path('table_datatable_basic/',chrevViews.table_datatable_basic,name="table-datatable-basic"),
	
	#Pages
	path('page_register/',chrevViews.page_register,name="page-register"),
	path('page_login/',chrevViews.page_login,name="page-login"),
	path('page_error_400/',chrevViews.page_error_400,name="page-error-400"),
	path('page_error_403/',chrevViews.page_error_403,name="page-error-403"),
	path('page_error_404/',chrevViews.page_error_404,name="page-error-404"),
	path('page_error_500/',chrevViews.page_error_500,name="page-error-500"),
	path('page_error_503/',chrevViews.page_error_503,name="page-error-503"),
	path('page_lock_screen/',chrevViews.page_lock_screen,name="page-lock-screen"),
	path('page_forgot_password/',chrevViews.page_forgot_password,name="page-forgot-password")
	

]

app/backend/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
	path("", views.HomeView.as_view(), name="home"),

]

app/backend/users/urls.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.urls import path

# --------------------------------------------------------------
# App imports
# --------------------------------------------------------------
from . import views

app_name = "users"

urlpatterns = [
    path('password/', views.change_password, name='change_password'),
    path('users/',views.users,name="users"),
	path('user-details/<uuid:id>/',views.user_details,name="user-details"),
	path('add-user/',views.add_user,name="add-user"),
	path('edit-user/<uuid:id>/',views.edit_user,name="edit-user"),
	path('delete-user/<uuid:id>/',views.delete_user,name="delete-user"),
	path('delete-multiple-user/',views.delete_multiple_user,name="delete-multiple-user"),
	path('register-device/',views.register_device,name="register-device"),
	path('deactivate-2fa/',views.deactivate_two_factor_auth,name="deactivate-2fa"),
	path('login/',views.login_user,name="login"),
	path('otp-login/',views.otp_login_user,name="otp-login"),
	path('logout/',views.logout,name="logout"),
	path('groups/',views.groups_list,name="groups"),
	path('group-edit/<int:id>/',views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',views.group_delete,name="group-delete"),
	path('group-add/',views.group_add,name="group-add"),
	path('permissions/',views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

app/backend/chrev/models.py
from django.db import models

# Create your models here.

app/backend/chrev/views.py
from django.shortcuts import redirect, render

app/backend/templates/chrev/elements/alert.html
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>

    <div class="alert alert-{{ message.tags }} alert  alert-dismissible alert-alt solid fade show">
        <div class="media">
            <div class="media-body">
                <p class="mb-0"> {{ message}}</p>
            </div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">
        </button>
    </div>

</li>
{% endfor %}
</ul>
{% endif %}

app/backend/templates/chrev/elements/footer.html
{% load static %}
<div class="footer">
    <div class="copyright">
        <p>Designed &amp; Developed by <a href="https://didcoding.com">Did Coding</a> {% now 'Y' %}</p>
    </div>
</div>

app/backend/templates/chrev/elements/messages.html
{% load static %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  
        
        <script type="text/javascript">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        toastr['success']('{{message}}', 'Success', {
            positionClass: 'toast-bottom-right',
            closeButton: true,
            progressBar: true,
            newestOnTop: true,
            rtl: $("body").attr("dir") === "rtl" || $("html").attr("dir") === "rtl",
            timeOut: 7500,
        });
        {% else %}
        toastr['error']('{{message}}', 'Error', {
            positionClass: 'toast-bottom-right',
            closeButton: true,
            progressBar: true,
            newestOnTop: true,
            rtl: $("body").attr("dir") === "rtl" || $("html").attr("dir") === "rtl",
            timeOut: 7500,
        });
        {% endif %}

        </script> 
        
        
        {% endif %}
    {% endfor %}
{% endif %}

app/backend/templates/chrev/elements/sidebar.html
{% load static %}

<div class="deznav">
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">




            {% if perms.users.view_customuser or perms.auth.view_group or perms.auth.view_permission %} 
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                <i class="flaticon-dashboard-1"></i>
                <span class="nav-text">Admin</span>
                {% comment %} <span class="badge badge-xs badge-danger ms-1">New</span> {% endcomment %}
            </a>
            <ul aria-expanded="false">

                {% if perms.users.view_customuser or perms.users.change_customuser or perms.users.add_customuser or perms.users.delete_customuser %}
                <li><a href="{% url 'users:users' %}">Users</a></li>
                {% endif %}
                {% if perms.auth.view_group or perms.auth.change_group or perms.auth.add_group or perms.auth.delete_group %}
                <li><a href="{% url 'users:groups' %}">Groups</a></li>
                {% endif %}
                {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                <li><a href="{% url 'users:permissions' %}">Permissions</a></li>
                {% endif %}
                {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                <li><a href="{% url 'users:assets' %}">Assets</a></li>
                {% endif %}
                {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                <li><a href="{% url 'users:invites' %}">Invites</a></li>
                {% endif %}
                {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                <li><a href="{% url 'users:companies' %}">Companies</a></li> 
                {% endif %}
                {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                <li><a href="{% url 'users:wallet-submissions' %}">Whitelist</a></li>
                {% endif %}
                {% if perms.auth.view_permission or perms.auth.change_permission or perms.auth.add_permission or  perms.auth.delete_permission%}
                <li><a href="{% url 'users:transaction-submissions' %}">Transactions</a></li>
                {% endif %}
            </ul>
        </li>
        {% endif %}




















            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-dashboard-1"></i>
                    <span class="nav-text">Dashboard</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'tokens:portfolio' %}">Portfolio</a></li>
                    {% comment %} <li><a href="{% url 'tokens:my-wallet' %}">My Wallet</a></li> {% endcomment %}
                    {% comment %} <li><a href="{% url 'tokens:coin-details' %}">Coin Details</a></li> {% endcomment %}
                    <li><a href="{% url 'tokens:transactions' %}">Transactions</a></li>
                    {% comment %} <li><a href="{% url 'tokens:market-capital' %}">Market Capital</a></li> {% endcomment %}
                </ul>
            </li>
            {% comment %} <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-app-store"></i>
                    <span class="nav-text">Apps</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'users:app-profile' %}">Profile</a></li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">Email</a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'chrev:email-compose' %}">Compose</a></li>
                            <li><a href="{% url 'chrev:email-inbox' %}">Inbox</a></li>
                            <li><a href="{% url 'chrev:email-read' %}">Read</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'chrev:app-calender' %}">Calendar</a></li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">Shop</a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'chrev:ecom-product-grid' %}">Product Grid</a></li>
                            <li><a href="{% url 'chrev:ecom-product-list' %}">Product List</a></li>
                            <li><a href="{% url 'chrev:ecom-product-detail' %}">Product Details</a></li>
                            <li><a href="{% url 'chrev:ecom-product-order' %}">Order</a></li>
                            <li><a href="{% url 'chrev:ecom-checkout' %}">Checkout</a></li>
                            <li><a href="{% url 'chrev:ecom-invoice' %}">Invoice</a></li>
                            <li><a href="{% url 'chrev:ecom-customers' %}">Customers</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-statistics"></i>
                    <span class="nav-text">Charts</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'chrev:chart-flot' %}">Flot</a></li>
                    <li><a href="{% url 'chrev:chart-morris' %}">Morris</a></li>
                    <li><a href="{% url 'chrev:chart-chartjs' %}">Chartjs</a></li>
                    <li><a href="{% url 'chrev:chart-chartist' %}">Chartist</a></li>
                    <li><a href="{% url 'chrev:chart-sparkline'%}">Sparkline</a></li>
                    <li><a href="{% url 'chrev:chart-peity' %}">Peity</a></li>
                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-exchange"></i>
                    <span class="nav-text">Bootstrap</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'chrev:ui-accordion' %}">Accordion</a></li>
                    <li><a href="{% url 'chrev:ui-alert' %}">Alert</a></li>
                    <li><a href="{% url 'chrev:ui-badge' %}">Badge</a></li>
                    <li><a href="{% url 'chrev:ui-button' %}">Button</a></li>
                    <li><a href="{% url 'chrev:ui-modal' %}">Modal</a></li>
                    <li><a href="{% url 'chrev:ui-button-group' %}">Button Group</a></li>
                    <li><a href="{% url 'chrev:ui-list-group' %}">List Group</a></li>
                    <li><a href="{% url 'chrev:ui-media-object' %}">Media Object</a></li>
                    <li><a href="{% url 'chrev:ui-card' %}">Cards</a></li>
                    <li><a href="{% url 'chrev:ui-carousel' %}">Carousel</a></li>
                    <li><a href="{% url 'chrev:ui-dropdown' %}">Dropdown</a></li>
                    <li><a href="{% url 'chrev:ui-popover' %}">Popover</a></li>
                    <li><a href="{% url 'chrev:ui-progressbar' %}">Progressbar</a></li>
                    <li><a href="{% url 'chrev:ui-tab' %}">Tab</a></li>
                    <li><a href="{% url 'chrev:ui-typography' %}">Typography</a></li>
                    <li><a href="{% url 'chrev:ui-pagination' %}">Pagination</a></li>
                    <li><a href="{% url 'chrev:ui-grid' %}">Grid</a></li>

                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-plugin"></i>
                    <span class="nav-text">Plugins</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'chrev:uc-select2' %}">Select 2</a></li>
                    <li><a href="{% url 'chrev:uc-nestable' %}">Nestedable</a></li>
                    <li><a href="{% url 'chrev:uc-noui-slider' %}">Noui Slider</a></li>
                    <li><a href="{% url 'chrev:uc-sweetalert' %}">Sweet Alert</a></li>
                    <li><a href="{% url 'chrev:uc-toastr' %}">Toastr</a></li>
                    <li><a href="{% url 'chrev:map-jqvmap' %}">Jqv Map</a></li>
                    <li><a href="{% url 'chrev:uc-lightgallery' %}">LightGallery</a></li>
                </ul>
            </li>
            <li><a href="{% url 'chrev:widget-basic' %}" class="ai-icon" aria-expanded="false">
                    <i class="flaticon-badge"></i>
                    <span class="nav-text">Widget</span>
                </a>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-form"></i>
                    <span class="nav-text">Forms</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'chrev:form-element' %}">Form Elements</a></li>
                    <li><a href="{% url 'chrev:form-wizard' %}">Wizard</a></li>
                    <li><a href="{% url 'chrev:form-ckeditor' %}">CkEditor</a></li>
                    <li><a href="{% url 'chrev:form-pickers' %}">Pickers</a></li>
                    <li><a href="{% url 'chrev:form-validation-jquery' %}">Jquery Validate</a></li>
                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-form-1"></i>
                    <span class="nav-text">Table</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'chrev:table-bootstrap-basic' %}">Bootstrap</a></li>
                    <li><a href="{% url 'chrev:table-datatable-basic' %}">Datatable</a></li>
                </ul>
            </li>
            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-contract"></i>
                    <span class="nav-text">Pages</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'chrev:page-register' %}">Register</a></li>
                    <li><a href="{% url 'chrev:page-login' %}">Login</a></li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">Error</a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'chrev:page-error-400' %}">Error 400</a></li>
                            <li><a href="{% url 'chrev:page-error-403' %}">Error 403</a></li>
                            <li><a href="{% url 'chrev:page-error-404' %}">Error 404</a></li>
                            <li><a href="{% url 'chrev:page-error-500' %}">Error 500</a></li>
                            <li><a href="{% url 'chrev:page-error-503' %}">Error 503</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'chrev:page-lock-screen' %}">Lock Screen</a></li>
                </ul>
            </li> {% endcomment %}
        </ul>
    
        {% comment %} <div class="add-menu-sidebar">
            <p>Generate Monthly Credit Report</p>
            <a href="javascript:void(0);">
            <svg width="24" height="12" viewBox="0 0 24 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M23.725 5.14889C23.7248 5.14861 23.7245 5.14828 23.7242 5.148L18.8256 0.272997C18.4586 -0.0922062 17.865 -0.0908471 17.4997 0.276184C17.1345 0.643169 17.1359 1.23675 17.5028 1.602L20.7918 4.875H0.9375C0.419719 4.875 0 5.29472 0 5.8125C0 6.33028 0.419719 6.75 0.9375 6.75H20.7917L17.5029 10.023C17.1359 10.3882 17.1345 10.9818 17.4998 11.3488C17.865 11.7159 18.4587 11.7172 18.8256 11.352L23.7242 6.477C23.7245 6.47672 23.7248 6.47639 23.7251 6.47611C24.0923 6.10964 24.0911 5.51414 23.725 5.14889Z" fill="white"/>
            </svg>
            </a>
        </div>
        <div class="copyright">
            <p><strong>Chrev - Crypto Admin Dashboard</strong> © 2022 All Rights Reserved</p>
            <p>Made with <i class="fa fa-heart"></i> by DexignZone</p>
        </div> {% endcomment %}
    </div>
</div>